version: '3.7'
services:
  basic-server-docker:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/app
    container_name: basic-server
    expose:
      - "6008"
    ports:
      - "6008:6006"
  mysql-db:
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env.mysql
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - basic-server-db-data:/var/lib/mysql
    networks:
      - basic-server
  seq:
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq:/data
    ports:
      - '8080:80' # exposes ui ports
      - '5341:5341' # handles ingestion http end-point
    image: 'datalust/seq:latest'
  cache:
    image: redis:7.2.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  basic-server-data:
  basic-server-db-data:
  seq:
  cache:
    driver: local
networks:
  basic-server:
  cache:
    driver: local

